//O2Ref:System.Web.Services.dll
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "LinqDBSoap", Namespace = "http://tempuri.org/")]
public partial class LinqDB : System.Web.Services.Protocols.SoapHttpClientProtocol
{

	private Credentials credentialsValueField;

	private System.Threading.SendOrPostCallback GetUserByIdOperationCompleted;

	private System.Threading.SendOrPostCallback GetUserByNameOperationCompleted;

	private System.Threading.SendOrPostCallback GetCurrentUserRolesOperationCompleted;

	private System.Threading.SendOrPostCallback GetUserRoleIdOperationCompleted;

	private System.Threading.SendOrPostCallback GetUserRoleTypeOperationCompleted;

	private System.Threading.SendOrPostCallback SetUserRoleIdOperationCompleted;

	private System.Threading.SendOrPostCallback DeleteGuidanceTypeOperationCompleted;

	private System.Threading.SendOrPostCallback GetDeletedGuidanceTypesIdsOperationCompleted;

	private System.Threading.SendOrPostCallback DeleteDeletedGuidanceTypesOperationCompleted;

	private System.Threading.SendOrPostCallback GetLibrariesOperationCompleted;

	private System.Threading.SendOrPostCallback GetFoldersOperationCompleted;

	private System.Threading.SendOrPostCallback GetAllGuidanceItemsOperationCompleted;

	private System.Threading.SendOrPostCallback GetGuidanceItemsInViewsOperationCompleted;

	private System.Threading.SendOrPostCallback GetGuidanceItemsInViewOperationCompleted;

	private System.Threading.SendOrPostCallback GetGuidanceItemsInLibraryOperationCompleted;

	private System.Threading.SendOrPostCallback GetGuidanceItemHtmlOperationCompleted;

	private System.Threading.SendOrPostCallback DeleteDeletedLibrariesOperationCompleted;

	private System.Threading.SendOrPostCallback GetDeletedLibrariesOperationCompleted;

	private System.Threading.SendOrPostCallback UnDeleteLibraryOperationCompleted;

	/// <remarks/>
	public LinqDB()
	{
		this.Url = "http://localhost:49999/WebServices/LinqDB.asmx";
	}

	public Credentials CredentialsValue {
		get { return this.credentialsValueField; }
		set { this.credentialsValueField = value; }
	}

	/// <remarks/>
	public event GetUserByIdCompletedEventHandler GetUserByIdCompleted;

	/// <remarks/>
	public event GetUserByNameCompletedEventHandler GetUserByNameCompleted;

	/// <remarks/>
	public event GetCurrentUserRolesCompletedEventHandler GetCurrentUserRolesCompleted;

	/// <remarks/>
	public event GetUserRoleIdCompletedEventHandler GetUserRoleIdCompleted;

	/// <remarks/>
	public event GetUserRoleTypeCompletedEventHandler GetUserRoleTypeCompleted;

	/// <remarks/>
	public event SetUserRoleIdCompletedEventHandler SetUserRoleIdCompleted;

	/// <remarks/>
	public event DeleteGuidanceTypeCompletedEventHandler DeleteGuidanceTypeCompleted;

	/// <remarks/>
	public event GetDeletedGuidanceTypesIdsCompletedEventHandler GetDeletedGuidanceTypesIdsCompleted;

	/// <remarks/>
	public event DeleteDeletedGuidanceTypesCompletedEventHandler DeleteDeletedGuidanceTypesCompleted;

	/// <remarks/>
	public event GetLibrariesCompletedEventHandler GetLibrariesCompleted;

	/// <remarks/>
	public event GetFoldersCompletedEventHandler GetFoldersCompleted;

	/// <remarks/>
	public event GetAllGuidanceItemsCompletedEventHandler GetAllGuidanceItemsCompleted;

	/// <remarks/>
	public event GetGuidanceItemsInViewsCompletedEventHandler GetGuidanceItemsInViewsCompleted;

	/// <remarks/>
	public event GetGuidanceItemsInViewCompletedEventHandler GetGuidanceItemsInViewCompleted;

	/// <remarks/>
	public event GetGuidanceItemsInLibraryCompletedEventHandler GetGuidanceItemsInLibraryCompleted;

	/// <remarks/>
	public event GetGuidanceItemHtmlCompletedEventHandler GetGuidanceItemHtmlCompleted;

	/// <remarks/>
	public event DeleteDeletedLibrariesCompletedEventHandler DeleteDeletedLibrariesCompleted;

	/// <remarks/>
	public event GetDeletedLibrariesCompletedEventHandler GetDeletedLibrariesCompleted;

	/// <remarks/>
	public event UnDeleteLibraryCompletedEventHandler UnDeleteLibraryCompleted;

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserById", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public User GetUserById(int userId)
	{
		object[] results = this.Invoke("GetUserById", new object[] { userId });
		return ((User)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetUserById(int userId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetUserById", new object[] { userId }, callback, asyncState);
	}

	/// <remarks/>
	public User EndGetUserById(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((User)(results[0]));
	}

	/// <remarks/>
	public void GetUserByIdAsync(int userId)
	{
		this.GetUserByIdAsync(userId, null);
	}

	/// <remarks/>
	public void GetUserByIdAsync(int userId, object userState)
	{
		if ((this.GetUserByIdOperationCompleted == null)) {
			this.GetUserByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByIdOperationCompleted);
		}
		this.InvokeAsync("GetUserById", new object[] { userId }, this.GetUserByIdOperationCompleted, userState);
	}

	private void OnGetUserByIdOperationCompleted(object arg)
	{
		if ((this.GetUserByIdCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetUserByIdCompleted(this, new GetUserByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByName", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public User GetUserByName(string userName)
	{
		object[] results = this.Invoke("GetUserByName", new object[] { userName });
		return ((User)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetUserByName(string userName, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetUserByName", new object[] { userName }, callback, asyncState);
	}

	/// <remarks/>
	public User EndGetUserByName(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((User)(results[0]));
	}

	/// <remarks/>
	public void GetUserByNameAsync(string userName)
	{
		this.GetUserByNameAsync(userName, null);
	}

	/// <remarks/>
	public void GetUserByNameAsync(string userName, object userState)
	{
		if ((this.GetUserByNameOperationCompleted == null)) {
			this.GetUserByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByNameOperationCompleted);
		}
		this.InvokeAsync("GetUserByName", new object[] { userName }, this.GetUserByNameOperationCompleted, userState);
	}

	private void OnGetUserByNameOperationCompleted(object arg)
	{
		if ((this.GetUserByNameCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetUserByNameCompleted(this, new GetUserByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentUserRoles", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string[] GetCurrentUserRoles()
	{
		object[] results = this.Invoke("GetCurrentUserRoles", new object[0]);
		return ((string[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetCurrentUserRoles(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetCurrentUserRoles", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public string[] EndGetCurrentUserRoles(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string[])(results[0]));
	}

	/// <remarks/>
	public void GetCurrentUserRolesAsync()
	{
		this.GetCurrentUserRolesAsync(null);
	}

	/// <remarks/>
	public void GetCurrentUserRolesAsync(object userState)
	{
		if ((this.GetCurrentUserRolesOperationCompleted == null)) {
			this.GetCurrentUserRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentUserRolesOperationCompleted);
		}
		this.InvokeAsync("GetCurrentUserRoles", new object[0], this.GetCurrentUserRolesOperationCompleted, userState);
	}

	private void OnGetCurrentUserRolesOperationCompleted(object arg)
	{
		if ((this.GetCurrentUserRolesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetCurrentUserRolesCompleted(this, new GetCurrentUserRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserRoleId", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public int GetUserRoleId(int userId)
	{
		object[] results = this.Invoke("GetUserRoleId", new object[] { userId });
		return ((int)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetUserRoleId(int userId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetUserRoleId", new object[] { userId }, callback, asyncState);
	}

	/// <remarks/>
	public int EndGetUserRoleId(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((int)(results[0]));
	}

	/// <remarks/>
	public void GetUserRoleIdAsync(int userId)
	{
		this.GetUserRoleIdAsync(userId, null);
	}

	/// <remarks/>
	public void GetUserRoleIdAsync(int userId, object userState)
	{
		if ((this.GetUserRoleIdOperationCompleted == null)) {
			this.GetUserRoleIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserRoleIdOperationCompleted);
		}
		this.InvokeAsync("GetUserRoleId", new object[] { userId }, this.GetUserRoleIdOperationCompleted, userState);
	}

	private void OnGetUserRoleIdOperationCompleted(object arg)
	{
		if ((this.GetUserRoleIdCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetUserRoleIdCompleted(this, new GetUserRoleIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserRoleType", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string GetUserRoleType(int userId)
	{
		object[] results = this.Invoke("GetUserRoleType", new object[] { userId });
		return ((string)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetUserRoleType(int userId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetUserRoleType", new object[] { userId }, callback, asyncState);
	}

	/// <remarks/>
	public string EndGetUserRoleType(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public void GetUserRoleTypeAsync(int userId)
	{
		this.GetUserRoleTypeAsync(userId, null);
	}

	/// <remarks/>
	public void GetUserRoleTypeAsync(int userId, object userState)
	{
		if ((this.GetUserRoleTypeOperationCompleted == null)) {
			this.GetUserRoleTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserRoleTypeOperationCompleted);
		}
		this.InvokeAsync("GetUserRoleType", new object[] { userId }, this.GetUserRoleTypeOperationCompleted, userState);
	}

	private void OnGetUserRoleTypeOperationCompleted(object arg)
	{
		if ((this.GetUserRoleTypeCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetUserRoleTypeCompleted(this, new GetUserRoleTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserRoleId", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool SetUserRoleId(int userId, int role)
	{
		object[] results = this.Invoke("SetUserRoleId", new object[] {
			userId,
			role
		});
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginSetUserRoleId(int userId, int role, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("SetUserRoleId", new object[] {
			userId,
			role
		}, callback, asyncState);
	}

	/// <remarks/>
	public bool EndSetUserRoleId(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void SetUserRoleIdAsync(int userId, int role)
	{
		this.SetUserRoleIdAsync(userId, role, null);
	}

	/// <remarks/>
	public void SetUserRoleIdAsync(int userId, int role, object userState)
	{
		if ((this.SetUserRoleIdOperationCompleted == null)) {
			this.SetUserRoleIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserRoleIdOperationCompleted);
		}
		this.InvokeAsync("SetUserRoleId", new object[] {
			userId,
			role
		}, this.SetUserRoleIdOperationCompleted, userState);
	}

	private void OnSetUserRoleIdOperationCompleted(object arg)
	{
		if ((this.SetUserRoleIdCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.SetUserRoleIdCompleted(this, new SetUserRoleIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteGuidanceType", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool DeleteGuidanceType(System.Guid guidanceTypeId)
	{
		object[] results = this.Invoke("DeleteGuidanceType", new object[] { guidanceTypeId });
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginDeleteGuidanceType(System.Guid guidanceTypeId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("DeleteGuidanceType", new object[] { guidanceTypeId }, callback, asyncState);
	}

	/// <remarks/>
	public bool EndDeleteGuidanceType(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void DeleteGuidanceTypeAsync(System.Guid guidanceTypeId)
	{
		this.DeleteGuidanceTypeAsync(guidanceTypeId, null);
	}

	/// <remarks/>
	public void DeleteGuidanceTypeAsync(System.Guid guidanceTypeId, object userState)
	{
		if ((this.DeleteGuidanceTypeOperationCompleted == null)) {
			this.DeleteGuidanceTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGuidanceTypeOperationCompleted);
		}
		this.InvokeAsync("DeleteGuidanceType", new object[] { guidanceTypeId }, this.DeleteGuidanceTypeOperationCompleted, userState);
	}

	private void OnDeleteGuidanceTypeOperationCompleted(object arg)
	{
		if ((this.DeleteGuidanceTypeCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.DeleteGuidanceTypeCompleted(this, new DeleteGuidanceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeletedGuidanceTypesIds", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public System.Guid[] GetDeletedGuidanceTypesIds()
	{
		object[] results = this.Invoke("GetDeletedGuidanceTypesIds", new object[0]);
		return ((System.Guid[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetDeletedGuidanceTypesIds(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetDeletedGuidanceTypesIds", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public System.Guid[] EndGetDeletedGuidanceTypesIds(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((System.Guid[])(results[0]));
	}

	/// <remarks/>
	public void GetDeletedGuidanceTypesIdsAsync()
	{
		this.GetDeletedGuidanceTypesIdsAsync(null);
	}

	/// <remarks/>
	public void GetDeletedGuidanceTypesIdsAsync(object userState)
	{
		if ((this.GetDeletedGuidanceTypesIdsOperationCompleted == null)) {
			this.GetDeletedGuidanceTypesIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeletedGuidanceTypesIdsOperationCompleted);
		}
		this.InvokeAsync("GetDeletedGuidanceTypesIds", new object[0], this.GetDeletedGuidanceTypesIdsOperationCompleted, userState);
	}

	private void OnGetDeletedGuidanceTypesIdsOperationCompleted(object arg)
	{
		if ((this.GetDeletedGuidanceTypesIdsCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetDeletedGuidanceTypesIdsCompleted(this, new GetDeletedGuidanceTypesIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteDeletedGuidanceTypes", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool DeleteDeletedGuidanceTypes()
	{
		object[] results = this.Invoke("DeleteDeletedGuidanceTypes", new object[0]);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginDeleteDeletedGuidanceTypes(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("DeleteDeletedGuidanceTypes", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public bool EndDeleteDeletedGuidanceTypes(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void DeleteDeletedGuidanceTypesAsync()
	{
		this.DeleteDeletedGuidanceTypesAsync(null);
	}

	/// <remarks/>
	public void DeleteDeletedGuidanceTypesAsync(object userState)
	{
		if ((this.DeleteDeletedGuidanceTypesOperationCompleted == null)) {
			this.DeleteDeletedGuidanceTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDeletedGuidanceTypesOperationCompleted);
		}
		this.InvokeAsync("DeleteDeletedGuidanceTypes", new object[0], this.DeleteDeletedGuidanceTypesOperationCompleted, userState);
	}

	private void OnDeleteDeletedGuidanceTypesOperationCompleted(object arg)
	{
		if ((this.DeleteDeletedGuidanceTypesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.DeleteDeletedGuidanceTypesCompleted(this, new DeleteDeletedGuidanceTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLibraries", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_Library[] GetLibraries()
	{
		object[] results = this.Invoke("GetLibraries", new object[0]);
		return ((TM_Library[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetLibraries(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetLibraries", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public TM_Library[] EndGetLibraries(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_Library[])(results[0]));
	}

	/// <remarks/>
	public void GetLibrariesAsync()
	{
		this.GetLibrariesAsync(null);
	}

	/// <remarks/>
	public void GetLibrariesAsync(object userState)
	{
		if ((this.GetLibrariesOperationCompleted == null)) {
			this.GetLibrariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLibrariesOperationCompleted);
		}
		this.InvokeAsync("GetLibraries", new object[0], this.GetLibrariesOperationCompleted, userState);
	}

	private void OnGetLibrariesOperationCompleted(object arg)
	{
		if ((this.GetLibrariesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetLibrariesCompleted(this, new GetLibrariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFolders", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_Folder[] GetFolders(System.Guid library)
	{
		object[] results = this.Invoke("GetFolders", new object[] { library });
		return ((TM_Folder[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetFolders(System.Guid library, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetFolders", new object[] { library }, callback, asyncState);
	}

	/// <remarks/>
	public TM_Folder[] EndGetFolders(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_Folder[])(results[0]));
	}

	/// <remarks/>
	public void GetFoldersAsync(System.Guid library)
	{
		this.GetFoldersAsync(library, null);
	}

	/// <remarks/>
	public void GetFoldersAsync(System.Guid library, object userState)
	{
		if ((this.GetFoldersOperationCompleted == null)) {
			this.GetFoldersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoldersOperationCompleted);
		}
		this.InvokeAsync("GetFolders", new object[] { library }, this.GetFoldersOperationCompleted, userState);
	}

	private void OnGetFoldersOperationCompleted(object arg)
	{
		if ((this.GetFoldersCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetFoldersCompleted(this, new GetFoldersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllGuidanceItems", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_GuidanceItem[] GetAllGuidanceItems()
	{
		object[] results = this.Invoke("GetAllGuidanceItems", new object[0]);
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetAllGuidanceItems(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetAllGuidanceItems", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public TM_GuidanceItem[] EndGetAllGuidanceItems(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public void GetAllGuidanceItemsAsync()
	{
		this.GetAllGuidanceItemsAsync(null);
	}

	/// <remarks/>
	public void GetAllGuidanceItemsAsync(object userState)
	{
		if ((this.GetAllGuidanceItemsOperationCompleted == null)) {
			this.GetAllGuidanceItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllGuidanceItemsOperationCompleted);
		}
		this.InvokeAsync("GetAllGuidanceItems", new object[0], this.GetAllGuidanceItemsOperationCompleted, userState);
	}

	private void OnGetAllGuidanceItemsOperationCompleted(object arg)
	{
		if ((this.GetAllGuidanceItemsCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetAllGuidanceItemsCompleted(this, new GetAllGuidanceItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGuidanceItemsInViews", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_GuidanceItem[] GetGuidanceItemsInViews(System.Guid[] viewIds)
	{
		object[] results = this.Invoke("GetGuidanceItemsInViews", new object[] { viewIds });
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetGuidanceItemsInViews(System.Guid[] viewIds, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetGuidanceItemsInViews", new object[] { viewIds }, callback, asyncState);
	}

	/// <remarks/>
	public TM_GuidanceItem[] EndGetGuidanceItemsInViews(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public void GetGuidanceItemsInViewsAsync(System.Guid[] viewIds)
	{
		this.GetGuidanceItemsInViewsAsync(viewIds, null);
	}

	/// <remarks/>
	public void GetGuidanceItemsInViewsAsync(System.Guid[] viewIds, object userState)
	{
		if ((this.GetGuidanceItemsInViewsOperationCompleted == null)) {
			this.GetGuidanceItemsInViewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuidanceItemsInViewsOperationCompleted);
		}
		this.InvokeAsync("GetGuidanceItemsInViews", new object[] { viewIds }, this.GetGuidanceItemsInViewsOperationCompleted, userState);
	}

	private void OnGetGuidanceItemsInViewsOperationCompleted(object arg)
	{
		if ((this.GetGuidanceItemsInViewsCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetGuidanceItemsInViewsCompleted(this, new GetGuidanceItemsInViewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGuidanceItemsInView", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_GuidanceItem[] GetGuidanceItemsInView(System.Guid viewId)
	{
		object[] results = this.Invoke("GetGuidanceItemsInView", new object[] { viewId });
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetGuidanceItemsInView(System.Guid viewId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetGuidanceItemsInView", new object[] { viewId }, callback, asyncState);
	}

	/// <remarks/>
	public TM_GuidanceItem[] EndGetGuidanceItemsInView(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public void GetGuidanceItemsInViewAsync(System.Guid viewId)
	{
		this.GetGuidanceItemsInViewAsync(viewId, null);
	}

	/// <remarks/>
	public void GetGuidanceItemsInViewAsync(System.Guid viewId, object userState)
	{
		if ((this.GetGuidanceItemsInViewOperationCompleted == null)) {
			this.GetGuidanceItemsInViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuidanceItemsInViewOperationCompleted);
		}
		this.InvokeAsync("GetGuidanceItemsInView", new object[] { viewId }, this.GetGuidanceItemsInViewOperationCompleted, userState);
	}

	private void OnGetGuidanceItemsInViewOperationCompleted(object arg)
	{
		if ((this.GetGuidanceItemsInViewCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetGuidanceItemsInViewCompleted(this, new GetGuidanceItemsInViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGuidanceItemsInLibrary", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_GuidanceItem[] GetGuidanceItemsInLibrary(System.Guid libraryId)
	{
		object[] results = this.Invoke("GetGuidanceItemsInLibrary", new object[] { libraryId });
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetGuidanceItemsInLibrary(System.Guid libraryId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetGuidanceItemsInLibrary", new object[] { libraryId }, callback, asyncState);
	}

	/// <remarks/>
	public TM_GuidanceItem[] EndGetGuidanceItemsInLibrary(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_GuidanceItem[])(results[0]));
	}

	/// <remarks/>
	public void GetGuidanceItemsInLibraryAsync(System.Guid libraryId)
	{
		this.GetGuidanceItemsInLibraryAsync(libraryId, null);
	}

	/// <remarks/>
	public void GetGuidanceItemsInLibraryAsync(System.Guid libraryId, object userState)
	{
		if ((this.GetGuidanceItemsInLibraryOperationCompleted == null)) {
			this.GetGuidanceItemsInLibraryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuidanceItemsInLibraryOperationCompleted);
		}
		this.InvokeAsync("GetGuidanceItemsInLibrary", new object[] { libraryId }, this.GetGuidanceItemsInLibraryOperationCompleted, userState);
	}

	private void OnGetGuidanceItemsInLibraryOperationCompleted(object arg)
	{
		if ((this.GetGuidanceItemsInLibraryCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetGuidanceItemsInLibraryCompleted(this, new GetGuidanceItemsInLibraryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGuidanceItemHtml", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string GetGuidanceItemHtml(System.Guid GuidanceItemId)
	{
		object[] results = this.Invoke("GetGuidanceItemHtml", new object[] { GuidanceItemId });
		return ((string)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetGuidanceItemHtml(System.Guid GuidanceItemId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetGuidanceItemHtml", new object[] { GuidanceItemId }, callback, asyncState);
	}

	/// <remarks/>
	public string EndGetGuidanceItemHtml(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public void GetGuidanceItemHtmlAsync(System.Guid GuidanceItemId)
	{
		this.GetGuidanceItemHtmlAsync(GuidanceItemId, null);
	}

	/// <remarks/>
	public void GetGuidanceItemHtmlAsync(System.Guid GuidanceItemId, object userState)
	{
		if ((this.GetGuidanceItemHtmlOperationCompleted == null)) {
			this.GetGuidanceItemHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuidanceItemHtmlOperationCompleted);
		}
		this.InvokeAsync("GetGuidanceItemHtml", new object[] { GuidanceItemId }, this.GetGuidanceItemHtmlOperationCompleted, userState);
	}

	private void OnGetGuidanceItemHtmlOperationCompleted(object arg)
	{
		if ((this.GetGuidanceItemHtmlCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetGuidanceItemHtmlCompleted(this, new GetGuidanceItemHtmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteDeletedLibraries", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool DeleteDeletedLibraries()
	{
		object[] results = this.Invoke("DeleteDeletedLibraries", new object[0]);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginDeleteDeletedLibraries(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("DeleteDeletedLibraries", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public bool EndDeleteDeletedLibraries(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void DeleteDeletedLibrariesAsync()
	{
		this.DeleteDeletedLibrariesAsync(null);
	}

	/// <remarks/>
	public void DeleteDeletedLibrariesAsync(object userState)
	{
		if ((this.DeleteDeletedLibrariesOperationCompleted == null)) {
			this.DeleteDeletedLibrariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDeletedLibrariesOperationCompleted);
		}
		this.InvokeAsync("DeleteDeletedLibraries", new object[0], this.DeleteDeletedLibrariesOperationCompleted, userState);
	}

	private void OnDeleteDeletedLibrariesOperationCompleted(object arg)
	{
		if ((this.DeleteDeletedLibrariesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.DeleteDeletedLibrariesCompleted(this, new DeleteDeletedLibrariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeletedLibraries", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public TM_Library[] GetDeletedLibraries()
	{
		object[] results = this.Invoke("GetDeletedLibraries", new object[0]);
		return ((TM_Library[])(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginGetDeletedLibraries(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("GetDeletedLibraries", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public TM_Library[] EndGetDeletedLibraries(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((TM_Library[])(results[0]));
	}

	/// <remarks/>
	public void GetDeletedLibrariesAsync()
	{
		this.GetDeletedLibrariesAsync(null);
	}

	/// <remarks/>
	public void GetDeletedLibrariesAsync(object userState)
	{
		if ((this.GetDeletedLibrariesOperationCompleted == null)) {
			this.GetDeletedLibrariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeletedLibrariesOperationCompleted);
		}
		this.InvokeAsync("GetDeletedLibraries", new object[0], this.GetDeletedLibrariesOperationCompleted, userState);
	}

	private void OnGetDeletedLibrariesOperationCompleted(object arg)
	{
		if ((this.GetDeletedLibrariesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.GetDeletedLibrariesCompleted(this, new GetDeletedLibrariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnDeleteLibrary", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool UnDeleteLibrary(System.Guid libraryId)
	{
		object[] results = this.Invoke("UnDeleteLibrary", new object[] { libraryId });
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginUnDeleteLibrary(System.Guid libraryId, System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("UnDeleteLibrary", new object[] { libraryId }, callback, asyncState);
	}

	/// <remarks/>
	public bool EndUnDeleteLibrary(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void UnDeleteLibraryAsync(System.Guid libraryId)
	{
		this.UnDeleteLibraryAsync(libraryId, null);
	}

	/// <remarks/>
	public void UnDeleteLibraryAsync(System.Guid libraryId, object userState)
	{
		if ((this.UnDeleteLibraryOperationCompleted == null)) {
			this.UnDeleteLibraryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnDeleteLibraryOperationCompleted);
		}
		this.InvokeAsync("UnDeleteLibrary", new object[] { libraryId }, this.UnDeleteLibraryOperationCompleted, userState);
	}

	private void OnUnDeleteLibraryOperationCompleted(object arg)
	{
		if ((this.UnDeleteLibraryCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.UnDeleteLibraryCompleted(this, new UnDeleteLibraryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	public new void CancelAsync(object userState)
	{
		base.CancelAsync(userState);
	}
}

/// <remarks/>





/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class TM_GuidanceItem
{

	private System.Guid idField;

	private string titleField;

	private string topicField;

	private string technologyField;

	private string categoryField;

	private string ruleTypeField;

	private string priorityField;

	private string statusField;

	private string authorField;

	private System.DateTime lastUpdateField;

	private string guidanceTypeField;

	private System.Guid libraryField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Guid Id {
		get { return this.idField; }
		set { this.idField = value; }
	}
	
	public System.Guid Id_Original { get; set;}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Title {
		get { return this.titleField; }
		set { this.titleField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Topic {
		get { return this.topicField; }
		set { this.topicField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Technology {
		get { return this.technologyField; }
		set { this.technologyField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Category {
		get { return this.categoryField; }
		set { this.categoryField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string RuleType {
		get { return this.ruleTypeField; }
		set { this.ruleTypeField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Priority {
		get { return this.priorityField; }
		set { this.priorityField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Status {
		get { return this.statusField; }
		set { this.statusField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Author {
		get { return this.authorField; }
		set { this.authorField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.DateTime LastUpdate {
		get { return this.lastUpdateField; }
		set { this.lastUpdateField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string GuidanceType {
		get { return this.guidanceTypeField; }
		set { this.guidanceTypeField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Guid Library {
		get { return this.libraryField; }
		set { this.libraryField = value; }
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class TM_Folder
{

	private System.Guid idField;

	private string nameField;

	private string captionField;

	private System.Guid libraryField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Guid Id {
		get { return this.idField; }
		set { this.idField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name {
		get { return this.nameField; }
		set { this.nameField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Caption {
		get { return this.captionField; }
		set { this.captionField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Guid Library {
		get { return this.libraryField; }
		set { this.libraryField = value; }
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class TM_Library
{

	private System.Guid idField;

	private string captionField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Guid Id {
		get { return this.idField; }
		set { this.idField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Caption {
		get { return this.captionField; }
		set { this.captionField = value; }
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
public partial class User
{

	private int userIDField;

	private string userNameField;

	private string passwordField;

	private string emailField;

	private string firstNameField;

	private string lastNameField;

	private int roleField;

	private bool activeField;

	private System.Nullable<System.DateTime> expirationDateField;

	private string titleField;

	private string companyField;

	/// <remarks/>
	public int UserID {
		get { return this.userIDField; }
		set { this.userIDField = value; }
	}

	/// <remarks/>
	public string UserName {
		get { return this.userNameField; }
		set { this.userNameField = value; }
	}

	/// <remarks/>
	public string Password {
		get { return this.passwordField; }
		set { this.passwordField = value; }
	}

	/// <remarks/>
	public string email {
		get { return this.emailField; }
		set { this.emailField = value; }
	}

	/// <remarks/>
	public string FirstName {
		get { return this.firstNameField; }
		set { this.firstNameField = value; }
	}

	/// <remarks/>
	public string LastName {
		get { return this.lastNameField; }
		set { this.lastNameField = value; }
	}

	/// <remarks/>
	public int Role {
		get { return this.roleField; }
		set { this.roleField = value; }
	}

	/// <remarks/>
	public bool Active {
		get { return this.activeField; }
		set { this.activeField = value; }
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
	public System.Nullable<System.DateTime> ExpirationDate {
		get { return this.expirationDateField; }
		set { this.expirationDateField = value; }
	}

	/// <remarks/>
	public string Title {
		get { return this.titleField; }
		set { this.titleField = value; }
	}

	/// <remarks/>
	public string Company {
		get { return this.companyField; }
		set { this.companyField = value; }
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetUserByIdCompletedEventHandler(object sender, GetUserByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetUserByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public User Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((User)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetUserByNameCompletedEventHandler(object sender, GetUserByNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetUserByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public User Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((User)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetCurrentUserRolesCompletedEventHandler(object sender, GetCurrentUserRolesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCurrentUserRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetCurrentUserRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public string[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((string[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetUserRoleIdCompletedEventHandler(object sender, GetUserRoleIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserRoleIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetUserRoleIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public int Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((int)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetUserRoleTypeCompletedEventHandler(object sender, GetUserRoleTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserRoleTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetUserRoleTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public string Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((string)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void SetUserRoleIdCompletedEventHandler(object sender, SetUserRoleIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetUserRoleIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal SetUserRoleIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DeleteGuidanceTypeCompletedEventHandler(object sender, DeleteGuidanceTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteGuidanceTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal DeleteGuidanceTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetDeletedGuidanceTypesIdsCompletedEventHandler(object sender, GetDeletedGuidanceTypesIdsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeletedGuidanceTypesIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetDeletedGuidanceTypesIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public System.Guid[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((System.Guid[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DeleteDeletedGuidanceTypesCompletedEventHandler(object sender, DeleteDeletedGuidanceTypesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteDeletedGuidanceTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal DeleteDeletedGuidanceTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetLibrariesCompletedEventHandler(object sender, GetLibrariesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetLibrariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetLibrariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_Library[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_Library[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetFoldersCompletedEventHandler(object sender, GetFoldersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetFoldersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetFoldersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_Folder[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_Folder[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetAllGuidanceItemsCompletedEventHandler(object sender, GetAllGuidanceItemsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAllGuidanceItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetAllGuidanceItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_GuidanceItem[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_GuidanceItem[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetGuidanceItemsInViewsCompletedEventHandler(object sender, GetGuidanceItemsInViewsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGuidanceItemsInViewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetGuidanceItemsInViewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_GuidanceItem[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_GuidanceItem[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetGuidanceItemsInViewCompletedEventHandler(object sender, GetGuidanceItemsInViewCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGuidanceItemsInViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetGuidanceItemsInViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_GuidanceItem[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_GuidanceItem[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetGuidanceItemsInLibraryCompletedEventHandler(object sender, GetGuidanceItemsInLibraryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGuidanceItemsInLibraryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetGuidanceItemsInLibraryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_GuidanceItem[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_GuidanceItem[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetGuidanceItemHtmlCompletedEventHandler(object sender, GetGuidanceItemHtmlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGuidanceItemHtmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetGuidanceItemHtmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public string Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((string)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DeleteDeletedLibrariesCompletedEventHandler(object sender, DeleteDeletedLibrariesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteDeletedLibrariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal DeleteDeletedLibrariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetDeletedLibrariesCompletedEventHandler(object sender, GetDeletedLibrariesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeletedLibrariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal GetDeletedLibrariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public TM_Library[] Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((TM_Library[])(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UnDeleteLibraryCompletedEventHandler(object sender, UnDeleteLibraryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UnDeleteLibraryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal UnDeleteLibraryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}
