//O2Ref:System.Web.Services.dll
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "TeamMentorSecuritySoap", Namespace = "http://tempuri.org/")]
public partial class TeamMentorSecurity : System.Web.Services.Protocols.SoapHttpClientProtocol
{

	private Credentials credentialsValueField;

	private System.Threading.SendOrPostCallback DemandPrivileges_AdminOperationCompleted;

	private System.Threading.SendOrPostCallback DemandPrivileges_ReadArticlesOperationCompleted;

	private System.Threading.SendOrPostCallback IsUserAdminOperationCompleted;

	/// <remarks/>
	public TeamMentorSecurity()
	{
		this.Url = "http://localhost:49999/WebServices/TeamMentorSecurity.asmx";
	}

	public Credentials CredentialsValue {
		get { return this.credentialsValueField; }
		set { this.credentialsValueField = value; }
	}

	/// <remarks/>
	public event DemandPrivileges_AdminCompletedEventHandler DemandPrivileges_AdminCompleted;

	/// <remarks/>
	public event DemandPrivileges_ReadArticlesCompletedEventHandler DemandPrivileges_ReadArticlesCompleted;

	/// <remarks/>
	public event IsUserAdminCompletedEventHandler IsUserAdminCompleted;

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DemandPrivileges_Admin", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string DemandPrivileges_Admin()
	{
		object[] results = this.Invoke("DemandPrivileges_Admin", new object[0]);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginDemandPrivileges_Admin(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("DemandPrivileges_Admin", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public string EndDemandPrivileges_Admin(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public void DemandPrivileges_AdminAsync()
	{
		this.DemandPrivileges_AdminAsync(null);
	}

	/// <remarks/>
	public void DemandPrivileges_AdminAsync(object userState)
	{
		if ((this.DemandPrivileges_AdminOperationCompleted == null)) {
			this.DemandPrivileges_AdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDemandPrivileges_AdminOperationCompleted);
		}
		this.InvokeAsync("DemandPrivileges_Admin", new object[0], this.DemandPrivileges_AdminOperationCompleted, userState);
	}

	private void OnDemandPrivileges_AdminOperationCompleted(object arg)
	{
		if ((this.DemandPrivileges_AdminCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.DemandPrivileges_AdminCompleted(this, new DemandPrivileges_AdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DemandPrivileges_ReadArticles", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string DemandPrivileges_ReadArticles()
	{
		object[] results = this.Invoke("DemandPrivileges_ReadArticles", new object[0]);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginDemandPrivileges_ReadArticles(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("DemandPrivileges_ReadArticles", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public string EndDemandPrivileges_ReadArticles(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string)(results[0]));
	}

	/// <remarks/>
	public void DemandPrivileges_ReadArticlesAsync()
	{
		this.DemandPrivileges_ReadArticlesAsync(null);
	}

	/// <remarks/>
	public void DemandPrivileges_ReadArticlesAsync(object userState)
	{
		if ((this.DemandPrivileges_ReadArticlesOperationCompleted == null)) {
			this.DemandPrivileges_ReadArticlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDemandPrivileges_ReadArticlesOperationCompleted);
		}
		this.InvokeAsync("DemandPrivileges_ReadArticles", new object[0], this.DemandPrivileges_ReadArticlesOperationCompleted, userState);
	}

	private void OnDemandPrivileges_ReadArticlesOperationCompleted(object arg)
	{
		if ((this.DemandPrivileges_ReadArticlesCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.DemandPrivileges_ReadArticlesCompleted(this, new DemandPrivileges_ReadArticlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	[System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserAdmin", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public bool IsUserAdmin()
	{
		object[] results = this.Invoke("IsUserAdmin", new object[0]);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public System.IAsyncResult BeginIsUserAdmin(System.AsyncCallback callback, object asyncState)
	{
		return this.BeginInvoke("IsUserAdmin", new object[0], callback, asyncState);
	}

	/// <remarks/>
	public bool EndIsUserAdmin(System.IAsyncResult asyncResult)
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((bool)(results[0]));
	}

	/// <remarks/>
	public void IsUserAdminAsync()
	{
		this.IsUserAdminAsync(null);
	}

	/// <remarks/>
	public void IsUserAdminAsync(object userState)
	{
		if ((this.IsUserAdminOperationCompleted == null)) {
			this.IsUserAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserAdminOperationCompleted);
		}
		this.InvokeAsync("IsUserAdmin", new object[0], this.IsUserAdminOperationCompleted, userState);
	}

	private void OnIsUserAdminOperationCompleted(object arg)
	{
		if ((this.IsUserAdminCompleted != null)) {
			System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
			this.IsUserAdminCompleted(this, new IsUserAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
		}
	}

	/// <remarks/>
	public new void CancelAsync(object userState)
	{
		base.CancelAsync(userState);
	}
}

/// <remarks/>





/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DemandPrivileges_AdminCompletedEventHandler(object sender, DemandPrivileges_AdminCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DemandPrivileges_AdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal DemandPrivileges_AdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public string Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((string)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DemandPrivileges_ReadArticlesCompletedEventHandler(object sender, DemandPrivileges_ReadArticlesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DemandPrivileges_ReadArticlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal DemandPrivileges_ReadArticlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public string Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((string)(this.results[0]));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void IsUserAdminCompletedEventHandler(object sender, IsUserAdminCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IsUserAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

	private object[] results;

	internal IsUserAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
	{
		this.results = results;
	}

	/// <remarks/>
	public bool Result {
		get {
			this.RaiseExceptionIfNecessary();
			return ((bool)(this.results[0]));
		}
	}
}
